import

In [1]:
import numpy as np

In [2]:
my_lst=[1,2,3,4,5]

creating one dimensional array

In [3]:
arr=np.array(my_lst)

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
mylst1=[6,7,8,9,10]

In [6]:
mylst2=[11,12,13,14,15]

creating multidimensional array

In [8]:
arr1=np.array([my_lst,mylst1,mylst2])

In [9]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


shape and reshape

In [11]:
arr1.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [12]:
arr.shape

(5,)

In [13]:
arr1.shape

(3, 5)

accessing

In [15]:
arr[2]

3

In [16]:
arr1[2,1]

12

In [17]:
arr1[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [18]:
arr1[:,3:]

array([[ 4,  5],
       [ 9, 10],
       [14, 15]])

In [19]:
arr1[1,:]

array([ 6,  7,  8,  9, 10])

In [20]:
arr1[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
arr1[1:2,3:4]

array([[9]])

In [29]:
arr1[1:3,2:5]

array([[ 8,  9, 10],
       [13, 14, 15]])

arrange

In [31]:
arrange=np.arange(0,10)

In [32]:
print(arrange)

[0 1 2 3 4 5 6 7 8 9]


In [33]:
arrange1=np.arange(0,10,2)

In [34]:
print(arrange1)

[0 2 4 6 8]


linespace

In [35]:
ls=np.linspace(1,10,50)

In [36]:
print(ls)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [37]:
ls[1]

1.183673469387755

In [38]:
ls[1]-ls[2]

-0.18367346938775508

In [39]:
ls[2]-ls[3]

-0.18367346938775508

boradcasting

In [40]:
arrange[3:]=100

In [41]:
print(arrange)

[  0   1   2 100 100 100 100 100 100 100]


copy and reference

In [43]:
arrcopy=arr

In [44]:
print(arr)

[1 2 3 4 5]


In [45]:
arrcopy[1:100]=500

In [46]:
print(arr,arrcopy)

[  1 500 500 500 500] [  1 500 500 500 500]


In [47]:
arrcopy=arr.copy()

In [48]:
arrcopy[3:]=888

In [50]:
print(arr,arrcopy)

[  1 500 500 500 500] [  1 500 500 888 888]


EDA

In [51]:
val=2

In [52]:
arr < val

array([ True, False, False, False, False])

In [53]:
print(arr[arr<val])

[1]


In [54]:
arr*2

array([   2, 1000, 1000, 1000, 1000])

ones 

In [57]:
np.ones(4)

array([1., 1., 1., 1.])

In [58]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [59]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

random distribution

In [60]:
np.random.rand(3,3)

array([[0.67370661, 0.69913123, 0.83514075],
       [0.98908684, 0.43262811, 0.85286041],
       [0.13580093, 0.82176665, 0.3667537 ]])

standard normal distribution

In [61]:
np.random.randn(4,4)

array([[ 1.02119086,  1.56148176,  0.56188034, -0.51669156],
       [-1.44614426, -1.34652566,  0.06395369, -0.46144357],
       [ 1.97079606, -1.17805582, -0.70020264, -0.81203269],
       [ 0.62536363,  1.12546612, -1.34535998,  0.9684519 ]])

randint

In [62]:
np.random.randint(0,100,8)

array([47, 56, 32, 23, 38, 29, 29,  4])

In [64]:
np.random.randint(0,100,8).shape

(8,)

In [65]:
np.random.randint(0,100,8).reshape(4,2)

array([[71, 38],
       [20, 64],
       [48, 49],
       [51, 24]])

random sample

In [66]:
np.random.random_sample((2,3))

array([[0.59203416, 0.40691289, 0.7843937 ],
       [0.01334122, 0.4219363 , 0.39468428]])